// <auto-generated />
using System;
using LabMaintenanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabMaintenanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LabMaintenanceAPI.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DeviceId");

                    b.HasIndex("LabId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LabId"));

                    b.Property<int?>("LabInchargeId")
                        .HasColumnType("int");

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LabId");

                    b.HasIndex("LabInchargeId");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.SoftwareRequest", b =>
                {
                    b.Property<int>("SoftwareRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SoftwareRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SoftwareRequestId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("SoftwareRequests");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RequestedBy");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.WorkLog", b =>
                {
                    b.Property<int>("WorkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkLogId"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("WorkLogId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TicketId");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Device", b =>
                {
                    b.HasOne("LabMaintenanceAPI.Models.Lab", "Lab")
                        .WithMany("Devices")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Lab", b =>
                {
                    b.HasOne("LabMaintenanceAPI.Models.User", "LabIncharge")
                        .WithMany("LabsManaged")
                        .HasForeignKey("LabInchargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LabIncharge");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.SoftwareRequest", b =>
                {
                    b.HasOne("LabMaintenanceAPI.Models.Device", "Device")
                        .WithMany("SoftwareRequests")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabMaintenanceAPI.Models.User", "Requester")
                        .WithMany("SoftwareRequests")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Ticket", b =>
                {
                    b.HasOne("LabMaintenanceAPI.Models.User", "Technician")
                        .WithMany("TicketsAssigned")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LabMaintenanceAPI.Models.Device", "Device")
                        .WithMany("Tickets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabMaintenanceAPI.Models.User", "Requester")
                        .WithMany("TicketsRequested")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Requester");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.WorkLog", b =>
                {
                    b.HasOne("LabMaintenanceAPI.Models.User", "Technician")
                        .WithMany("WorkLogs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabMaintenanceAPI.Models.Ticket", "Ticket")
                        .WithMany("WorkLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Device", b =>
                {
                    b.Navigation("SoftwareRequests");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Lab", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.Ticket", b =>
                {
                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("LabMaintenanceAPI.Models.User", b =>
                {
                    b.Navigation("LabsManaged");

                    b.Navigation("SoftwareRequests");

                    b.Navigation("TicketsAssigned");

                    b.Navigation("TicketsRequested");

                    b.Navigation("WorkLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
